---
defaults: &defaults
  environment:
    GOOGLE_PROJECT_ID: planet-4-151612
  docker:
    - image: greenpeaceinternational/circleci-base:latest
  working_directory: /home/circleci/app

version: 2

jobs:
  build-push-tag:
    <<: *defaults
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout
      - run: docker-login.sh
      - run: make build-tag push-tag
  build-push-branch:
    <<: *defaults
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout
      - run: docker-login.sh
      - run: make build-branch push-branch

  check-rss:
    docker:
      - image: greenpeaceinternational/planet4-vulnerable-plugins-rss:master
    steps:
      - run: php /app/rss.php

workflows:
  version: 2
  branch:
    jobs:
      - build-push-branch:
          context: org-global
          filters:
            branches:
              ignore: develop
      - check-rss:
          context: org-global
          requires:
            - build-push-branch

  tag:
    jobs:
      - build-push-tag:
          context: org-global
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

  check-rss:
    triggers:
      - schedule:
          cron: "32 * * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - check-rss:
          context: org-global
